In [2]:
!pip uninstall -y torch
!pip install torch


  Using cached torch-2.3.0-cp311-cp311-win_amd64.whl.metadata (26 kB)
  Using cached filelock-3.14.0-py3-none-any.whl.metadata (2.8 kB)
  Using cached sympy-1.12-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached fsspec-2024.5.0-py3-none-any.whl.metadata (11 kB)
  Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.4 kB)
  Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.2 kB)
  Using cached tbb-2021.12.0-py3-none-win_amd64.whl.metadata (1.1 kB)
  Using cached MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.3.0-cp311-cp311-win_amd64.whl (159.8 MB)
Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
Using cached tbb-2021.12.0-py3-none-win_amd64.whl (2

In [4]:
pip install transformers


     ---------------------------------------- 0.0/43.8 kB ? eta -:--:--
     --------- ------------------------------ 10.2/43.8 kB ? eta -:--:--
     -------------------------- ----------- 30.7/43.8 kB 325.1 kB/s eta 0:00:01
     -------------------------------------- 43.8/43.8 kB 357.2 kB/s eta 0:00:00
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------------- ------------- 41.0/61.0 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 42.0/42.0 kB 1.0 MB/s eta 0:00:00
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ---------------------------------------- 57.6/57.6 kB 3.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.1 MB 6.8 MB/s eta 0:00:02
   - ---------

In [6]:
pip install pandas


   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB 1.4 MB/s eta 0:00:09
   ---------------------------------------- 0.1/11.6 MB 825.8 kB/s eta 0:00:15
   ---------------------------------------- 0.1/11.6 MB 1.0 MB/s eta 0:00:12
    --------------------------------------- 0.2/11.6 MB 1.2 MB/s eta 0:00:10
    --------------------------------------- 0.2/11.6 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.3/11.6 MB 1.2 MB/s eta 0:00:10
   - -------------------------------------- 0.4/11.6 MB 1.3 MB/s eta 0:00:09
   - -------------------------------------- 0.5/11.6 MB 1.3 MB/s eta 0:00:09
   - -------------------------------------- 0.5/11.6 MB 1.3 MB/s eta 0:00:09
   -- ------------------------------------- 0.6/11.6 MB 1.4 MB/s eta 0:00:09
   -- ------------------------------------- 0.7/11.6 MB 1.4 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/11.6 MB 1.4 MB/s eta 0:00:08
   -

In [8]:
pip install tensorflow


     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------- --------------------- 20.5/46.2 kB 640.0 kB/s eta 0:00:01
     --------------------------------- ---- 41.0/46.2 kB 653.6 kB/s eta 0:00:01
     -------------------------------------- 46.2/46.2 kB 571.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/377.0 MB 435.7 kB/s eta 0:14:26
   ---------------------------------------- 0.1/377.0 MB 465.5 kB/s eta 0:13:30
   ---------------------------------------- 0.1/377.0 MB 521.8 kB/s eta 0:12:03
   ---------------------------------------- 0.1/377.0 MB 544.7 kB/s eta 0:11:32
   ---------------------------------------- 0.1/377.0 MB 566.5 kB/s eta 0:11:06
   ---------------------------------------- 0.2/377.0 MB 551.6 kB/s eta 0:11:24
   ---------------------------------------- 0.2/377.0 MB 565.6 kB/

In [9]:
import torch
from transformers import AutoTokenizer, AutoModel
import pandas as pd
import numpy as np
import os
import csv
import torch.nn as nn
import tensorflow as tf
import ast



In [10]:
import tensorflow.keras as keras

In [12]:
pip install scikit-learn


     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.6 kB 330.3 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 541.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.0 MB 2.0 MB/s eta 0:00:06
    --------------------------------------- 0.1/11.0 MB 1.7 MB/s eta 0:00:07
    --------------------------------------- 0.3/11.0 MB 1.8 MB/s eta 0:00:07
   - -------------------------------------- 0.5/11.0 MB 2.9 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/11.0 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.0 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.0 MB 5.2 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/11.0 MB 6.4 MB/s eta 0:00:02
   ------

In [13]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.utils import shuffle
from sklearn.base import BaseEstimator, ClassifierMixin
import numpy as np
import tensorflow as tf
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.utils import shuffle
from sklearn.base import BaseEstimator, ClassifierMixin


In [14]:
# Load CodeBERT tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("microsoft/codebert-base")
model = AutoModel.from_pretrained("microsoft/codebert-base")

c:\Users\israt\OneDrive\Desktop\Alloy 5\Alloy-Codes-Version-5.1.0-\Dataset\.venv\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [15]:
# Define the RNN model
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

        out, _ = self.rnn(x, h0)

        out = self.fc(out[:, -1, :])
        return out


In [16]:
# Define RNN parameters
input_size = 768  # Size of the embedding vectors
hidden_size = 256  # Size of the hidden state of the RNN
num_layers = 2  # Number of layers in the RNN
output_size = 768  # Size of the output of the RNN
rnn_model = RNN(input_size, hidden_size, num_layers, output_size)

In [17]:
# Function to read the contents of a file
def read_file(file_path):
    with open(file_path, 'r') as file:
        return file.read()


In [18]:
# Function to process each chunk and generate embeddings
def process_chunk(chunk, tokenizer, model):
    # Tokenize the chunk
    inputs = tokenizer(chunk, return_tensors="pt", truncation=True, padding=True, max_length=512)

    # Generate embeddings
    with torch.no_grad():
        outputs = model(**inputs)
        embeddings = outputs.last_hidden_state
        attention_mask = inputs['attention_mask']

    return embeddings, attention_mask


In [20]:
# Function to process each file and handle long sequences
def process_file(file_path, tokenizer, model, max_length=512):
    content = read_file(file_path)

    # Tokenize the entire content to get tokens
    tokens = tokenizer.tokenize(content)

    # Split the tokens into chunks of max_length
    chunks = [tokens[i:i + max_length] for i in range(0, len(tokens), max_length)]

    # Convert chunks back to text
    chunk_texts = [tokenizer.convert_tokens_to_string(chunk) for chunk in chunks]

    # Process each chunk and collect embeddings and attention masks
    all_embeddings = []
    all_attention_masks = []
    for chunk_text in chunk_texts:
        embeddings, attention_mask = process_chunk(chunk_text, tokenizer, model)
        all_embeddings.append(embeddings)
        all_attention_masks.append(attention_mask)

    # Concatenate all embeddings and attention masks along the sequence dimension
    all_embeddings = torch.cat(all_embeddings, dim=1)
    all_attention_masks = torch.cat(all_attention_masks, dim=1)

    # Mask the embeddings
    masked_embeddings = all_embeddings * all_attention_masks.unsqueeze(-1)

    # Compute the mean-pooled embedding
    mean_pooled_embedding = masked_embeddings.sum(dim=1) / all_attention_masks.sum(dim=1).unsqueeze(-1)

    return mean_pooled_embedding

In [21]:
def one_hot_encode(solver_names, best_solver, max_length):
    # Create a dictionary to map solver names to indices
    solver_indices = {solver: i for i, solver in enumerate(solver_names)}

    if best_solver is None:
        # Return a default one-hot encoded vector when best_solver is None
        return np.zeros(max_length)
    else:
        # Get the index of the best solver
        best_solver_index = solver_indices[best_solver]

        # Create a one-hot encoded vector
        one_hot_vector = tf.one_hot(best_solver_index, len(solver_names)).numpy()

        # Pad the one-hot vector to the maximum length
        padded_one_hot_vector = np.zeros(max_length)
        padded_one_hot_vector[:len(one_hot_vector)] = one_hot_vector

        return padded_one_hot_vector

In [29]:
def find_best_solver(data):
    memory_constraint = data['Memory'].min()
    time_constraint = data['Execution Time'].min()

    # Set the upper bounds based on constraints
    memory_constraint2 = data['Memory'].max()
    time_constraint2 = data['Execution Time'].max()

    # Filter the solvers based on memory allocation and time consumption
    filtered_data = data[(data['Memory'] >= memory_constraint) & (data['Memory'] <= memory_constraint2) &
                         (data['Execution Time'] >= time_constraint) & (data['Execution Time'] <= time_constraint2)]

    # Find the solver with the lowest memory allocation and execution time
    if not filtered_data.empty:
        best_solver = filtered_data.sort_values(by=['Memory', 'Execution Time']).iloc[0]
        return best_solver['Solver Name'], best_solver['Memory'], best_solver['Execution Time']
    else:
        return None, None, None

In [35]:
def find_label(file_path, max_length):
    # Initialize the list to store encoded vectors
    encoded_vectors = []

    # Read the data
    data = pd.read_csv(file_path)

    # Find the best solver for the current CSV file
    best_solver, time, memory = find_best_solver(data)
    print(f"Best Solver for {file_path}: {best_solver} {time} {memory}")

    # One-hot encode the best solver
    solver_names = data['Solver Name'].unique()
    one_hot_vector = one_hot_encode(solver_names, best_solver, max_length)

    if np.all(one_hot_vector == 0):
        one_hot_vector = np.zeros(max_length)  # If no solver is found, then put all the values to zero

    print(one_hot_vector)

    # Append the encoded vector to the list
    encoded_vectors.append(one_hot_vector)

    # Convert the list of encoded vectors into a numpy array
    encoded_array = np.array(encoded_vectors)

    return encoded_array


In [36]:
def process_folder(folder_path):
    all_encoded_vectors = []
    max_length = 0

    # First pass: determine the maximum length of the one-hot vectors
    for file_name in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file_name)
        if os.path.isfile(file_path):
            data = pd.read_csv(file_path)
            solver_names = data['Solver Name'].unique()
            if len(solver_names) > max_length:
                max_length = len(solver_names)

    # Second pass: generate the one-hot encoded vectors with padding
    for file_name in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file_name)
        if os.path.isfile(file_path):
            encoded_vectors = find_label(file_path, max_length)
            all_encoded_vectors.extend(encoded_vectors)
    return np.array(all_encoded_vectors)

In [45]:
import os
encoded_vectors = []
test_folder = test_folder = 'C:/Users/israt/OneDrive/Desktop/Alloy 5/Alloy-Codes-Version-5.1.0-/Dataset/A4F-1B-ATR\All'
encoder_folder = 'CSV File/Output/Output/Output_AVG'

# List all the .als files in the Test folder
als_files = [f for f in os.listdir(test_folder) if f.endswith('.als')]

# List all the CSV files in the Encoder folder
csv_files = [f for f in os.listdir(encoder_folder) if f.endswith('.csv')]

# Create dictionaries to store filenames without extensions as keys and their full paths as values
als_dict = {os.path.splitext(os.path.basename(file))[0]: os.path.join(test_folder, file) for file in als_files}
csv_dict = {os.path.splitext(os.path.basename(file))[0].replace("AVG_", ""): os.path.join(encoder_folder, file) for file in csv_files}


# Assuming you have defined process_file, tokenizer, model, and rnn_model elsewhere in your code

# Iterate through the keys in als_dict and check if they exist in csv_dict
# Create output.csv file
with open('C:/Users/israt/OneDrive/Desktop/Alloy 5/Alloy-Codes-Version-5.1.0-/Dataset/output.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Filename', 'RNN Output'])
    for als_name, als_path in als_dict.items():
        if als_name in csv_dict:
            # If there is a match, print the matched filenames
            print(f"Matched: {als_path} and {csv_dict[als_name]}")

            # Assuming process_file function is defined elsewhere
            # Generate RNN output for the file, passing the full path of the .als file
            rnn_output = process_file(als_path, tokenizer, model, rnn_model)
            print(f"Mean-Pooled Embedding size for {als_name}: {rnn_output.size()}")
            rnn_output_list = rnn_output.squeeze().tolist()
            find_label(csv_dict[als_name])


            writer.writerow([als_name, rnn_output_list])

        else:
            # If no match is found, print a message
            print(f"No matching CSV file found for {als_path}")
encoded_array = np.array(encoded_vectors)
print(encoded_array)

Matched: C:/Users/israt/OneDrive/Desktop/Alloy 5/Alloy-Codes-Version-5.1.0-/Dataset/A4F-1B-ATR\All\classroom_inv10_1.als and CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_1.csv


TypeError: 'RNN' object cannot be interpreted as an integer

In [37]:
folder_path = 'CSV File/Output/Output/Output_AVG'
labels = process_folder(folder_path)
print(labels)

Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_1.csv: CryptoMiniSatJNI 21872 1679
[0. 0. 0. 1. 0. 0. 0. 0.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_10.csv: Sat4j 21872 1689
[0. 1. 0. 0. 0. 0. 0. 0.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_11.csv: None None None
[0. 0. 0. 0. 0. 0. 0. 0.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_12.csv: Minisat 21872 1713
[1. 0. 0. 0. 0. 0. 0. 0.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_13.csv: Lingeling 21872 1719
[0. 0. 0. 0. 0. 0. 0. 1.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_14.csv: Sat4j 21872 1743
[0. 1. 0. 0. 0. 0. 0. 0.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_15.csv: Lingeling 21872 1677
[0. 0. 0. 0. 0. 0. 0. 1.]
Best Solver for CSV File/Output/Output/Output_AVG\AVG_classroom_inv10_16.csv: Glucose41JNI 21872 1786
[0. 0. 0. 0. 0. 1. 0. 0.]
Best So